# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20160601_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
