# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_auto_20160607_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='url',
            new_name='imageLink',
        ),
        migrations.AddField(
            model_name='album',
            name='listenLink',
            field=models.CharField(default='<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=1108322766/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=none/transparent=true/" seamless><a href="http://brassphantoms.bandcamp.com/album/city-of-wolves-ep">City of Wolves EP by Brass Phantoms</a></iframe>', max_length=150),
        ),
    ]
